blank_issues_enabled: false
contact_links:
    - name: Documentation Issue
      url: https://github.com/Bizmex
      about: This issue tracker is not for documentation issues. Consider contacting us directly.
    - name: Questions and Help
      url: https://github.com/Bizmex/risper/discussions/categories/questions
      about: This issue tracker is not for support questions. Please refer to the Risper community's help and discussion forums.
